"""fixl models

Revision ID: 04a382f16ce8
Revises: 1c5d49ef5a52
Create Date: 2025-04-14 17:53:51.582230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04a382f16ce8'
down_revision: Union[str, None] = '1c5d49ef5a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('question_id', sa.Integer(), nullable=False))
    op.add_column('submissions', sa.Column('is_correct', sa.Boolean(), nullable=False))
    op.add_column('submissions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'submissions', 'questions', ['question_id'], ['id'])
    op.drop_column('submissions', 'submitted_at')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.add_column('submissions', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'is_correct')
    op.drop_column('submissions', 'question_id')
    # ### end Alembic commands ###
