"""fixl models

Revision ID: de44bfe94acb
Revises: 86bcc76ba6bf
Create Date: 2025-04-09 21:20:48.192904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de44bfe94acb'
down_revision: Union[str, None] = '86bcc76ba6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submitted_at', sa.DateTime(), nullable=False))
    op.drop_constraint('submissions_question_id_fkey', 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'created_at')
    op.drop_column('submissions', 'question_id')
    op.drop_column('submissions', 'is_correct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.create_foreign_key('submissions_question_id_fkey', 'submissions', 'questions', ['question_id'], ['id'])
    op.drop_column('submissions', 'submitted_at')
    # ### end Alembic commands ###
